# 应用名称
spring:
  application:
    name: zuul-proxy
server:
  port: 9910
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://cije:123456@localhost:8804/eureka/
zuul:
  # 给网关路由添加前缀
  prefix: /api
  routes: #给服务配置路由
    user-service:
      path: /userService/**
    feign-service:
      path: /feignService/**
      #关闭默认路由配置
  #  ignored-services: user-service,feign-service
  # 配置过滤敏感的请求头信息，设置为空就不会过滤
  sensitive-headers: Cookie,Set-Cookie,Authorization
  # 设置为true重定向是会添加host请求头
  add-host-header: true
  # 禁用过滤器
  PreLogFilter:
    pre:
      disable: false

# 开启查看路由的端点
management:
  endpoints:
    web:
      exposure:
        include: 'routes'


