spring:
  application:
    name: hystrix-service
server:
  port: 9905
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://cije:123456@localhost:8804/eureka/
service-url:
  user-service: http://user-service