POST http://localhost:9932/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic admin admin123456

grant_type=password&scope=all&username=test1&password=123456

### refresh_token
POST http://localhost:9932/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic admin admin123456

grant_type=refresh_token&scope=all&refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJ0ZXN0MSIsInNjb3BlIjpbImFsbCJdLCJhdGkiOiJlY2IxZjBiMS0xODk0LTRlMTAtOWM5Zi1jZjgwNmNiNzQxZjYiLCJleHAiOjE2MTk4NjAyMTEsImF1dGhvcml0aWVzIjpbImNsaWVudCJdLCJqdGkiOiI0Y2Y0OTA3MS1hMWEyLTQ0NDktYjM2OC0wMTg1ZjE1ODBmYzUiLCJjbGllbnRfaWQiOiJhZG1pbiIsImVuaGFuY2UiOiJlbmhhbmNlIGluZm8ifQ.4ImIfmG3NtiUVarFoPl2V6bShQ1NDUOE2iAK0L4bIQ0

###
GET http://localhost:9932/user/getCurrentUser
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJ0ZXN0MSIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2MTg5OTk1ODMsImF1dGhvcml0aWVzIjpbImNsaWVudCJdLCJqdGkiOiJhYWE0NDUxYS03MzFlLTRmM2QtYWU3MS01NWI0NTY3NTFhOTkiLCJjbGllbnRfaWQiOiJhZG1pbiIsImVuaGFuY2UiOiJlbmhhbmNlIGluZm8ifQ.4tntAn_VIyZXMs_RQx2czZw-FLB2NGUPgcUoH68_j4w