# 应用名称
spring:
  application:
    name: oauth2-client
oauth2-server-url: http://localhost:9932
security:
  oauth2: #与oauth2-server对应的配置
    client:
      client-id: admin
      client-secret: admin123456
      user-authorization-uri: ${oauth2-server-url}/oauth/authorize
      access-token-uri: ${oauth2-server-url}/oauth/token
    resource:
      jwt:
        key-uri: ${oauth2-server-url}/oauth/token_key
server:
  port: 9938
  servlet:
    session:
      cookie:
        # 防止Cookie冲突，冲突会导致登录验证不通过
        name: OAUTH2-CLIENT-SESSIONID
