### 演示从配置中心获取配置
GET http://localhost:9912/configInfo

### refresh
POST http://localhost:9912/actuator/refresh

### security
GET http://localhost:9914/configInfo

### cluster
GET http://localhost:9917/configInfo
### bus刷新
POST http://localhost:9918/actuator/bus-refresh

### bus刷新
POST http://localhost:9918/actuator/bus-refresh/config-client:9919

### amqp1
GET http://localhost:9919/configInfo

### amqp2
GET http://localhost:9920/configInfo