# 获取配置信息
# /{label}/{application}-{profile}
# 获取配置文件信息
# /{label}/{application}-{profile}.yml
# application：代表应用名称，默认为配置文件中的spring.application.name，如果配置了spring.cloud.config.name，则为该名称；
# label：代表分支名称，对应配置文件中的spring.cloud.config.label；
# profile：代表环境名称，对应配置文件中的spring.cloud.config.profile。
### master分支上dev环境的配置信息
GET http://localhost:9911/master/config-dev

### 获取master分支上dev环境的配置文件信息
GET http://localhost:9911/master/config-dev.yml

### 获取master分支上test环境的配置文件信息
GET http://localhost:9911/master/config-test.yml

### 获取dev分支上dev环境的配置文件信息
GET http://localhost:9911/dev/config-dev.yml