spring:
  application:
    name: eureka-server
server:
  port: 8803
eureka:
  instance:
    hostname: replica2
  client:
    register-with-eureka: true
    fetchRegistry: true
    # 声明注册中心的地址
    service-url:
      defaultZone: http://replica1:8802/eureka