# 应用名称
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: remote_route #路由的ID
          uri: ${service-url.user-service} #匹配后路由地址
          predicates: # 断言，路径相匹配的进行路由
            - RemoteAddr=127.0.0.1/24
server:
  port: 9921
service-url:
  user-service: http://localhost:9902

