spring:
  application:
    name: gateway-test1
server:
  port: 9960
# 配置输出日志
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
#开启端点
management:
  endpoints:
    web:
      exposure:
        include: '*'