# 应用名称
spring:
  application:
    name: eureka-security-server
  security:
    user:
      # 配置SpringSecurity用户名和密码
      name: cije
      password: 123456
server:
  port: 8804
eureka:
  instance:
    hostname: localhost
  client:
    # 不注册自己
    register-with-eureka: false
    # 不主动发现别人
    fetch-registry: false


