spring:
  application:
    name: gateway-test2
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      dynamic:
        data-id: gateway-router
        group: DEFAULT_GROUP
server:
  port: 9961
# 配置输出日志
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
#开启端点
management:
  endpoints:
    web:
      exposure:
        include: '*'