spring:
  application:
    name: eureka-client
server:
  port: 9901
eureka:
  client:
    # 注册到Eureka的注册中心
    register-with-eureka: true
    # 获取注册实例列表
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8801/eureka/ #配置注册中心地址