spring:
  application:
    name: eureka-client
server:
  port: 9901
eureka:
  client:
    # 注册到Eureka的注册中心
    register-with-eureka: true
    # 获取注册实例列表
    fetch-registry: true
    service-url:
      # 配置注册中心地址
      defaultZone: http://replica1:8802/eureka/,http://replica2:8803/eureka/