spring:
  application:
    name: nacos-ribbon-service
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
server:
  port: 9925
management:
  endpoints:
    web:
      exposure:
        include: '*'
service-url:
  nacos-user-service: http://nacos-user-service