spring:
  application:
    name: admin-server
  security:
    user:
      name: cije
      password: 123456
  boot: # 不显示admin-security-server的监控信息
    admin:
      discovery:
        ignored-services: ${spring.application.name}
server:
  port: 9922
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://cije:123456@localhost:8804/eureka/

