# 应用名称
spring:
  application:
    name: ribbon-service
#  zipkin:
#    base-url: http://localhost:9411
#    sleuth:
#      sampler:
#        probability: 0.1 #设置Sleuth的抽样收集概率
server:
  port: 9904
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://cije:123456@localhost:8804/eureka/
service-url:
  user-service: http://user-service
  user-service-ip: http://localhost:9902

